//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libya.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Etnik
    {
        public int Id { get; set; }
        [Display(Name ="Etnik Kök")]
        [Required(ErrorMessage ="Bu Alan Boþ Geçilemez")]
        public string etnikKok { get; set; }
        [Display(Name = "Yaþanýlan Þehir")]
        [Required(ErrorMessage = "Bu Alan Boþ Geçilemez")]
        public string eysehiri { get; set; }
        [Display(Name = "Etnik Kök Hakkýnda")]
        [Required(ErrorMessage = "Bu Alan Boþ Geçilemez")]
        public string ehakkinda { get; set; }
    }
}
