//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libya.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sehirler
    {
        public int Id { get; set; }

        [Display(Name ="Sıra")]
        [Required(ErrorMessage ="Bu Alan Boş Geçilemez ")]
        public Nullable<int> sıra { get; set; }
        [Display(Name = "Telefon Kodu")]
        [Required(ErrorMessage = "Bu Alan Boş Geçilemez ")]
        public string telefonKodu { get; set; }
        [Display(Name = "Şehir Adı")]
        [Required(ErrorMessage = "Bu Alan Boş Geçilemez ")]
        public string sehirAdı { get; set; }
        [Display(Name = "Nüfus")]
        [Required(ErrorMessage = "Bu Alan Boş Geçilemez ")]
        public string nufus { get; set; }
        [Display(Name = "Yüzölçümü")]
        [Required(ErrorMessage = "Bu Alan Boş Geçilemez ")]
        public string yuzolcum { get; set; }
        [Display(Name = "Bölge")]
        [Required(ErrorMessage = "Bu Alan Boş Geçilemez ")]
        public string bölge { get; set; }
    }
}
