//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libya.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Yerler
    {
        public int Id { get; set; }
        [Display(Name = "Yer Adı")]
        [Required(ErrorMessage = "Bu Alan Boş Geçilemez ")]
        public string yerAdı { get; set; }
        [Display(Name = "Şehiri")]
        [Required(ErrorMessage = "Bu Alan Boş Geçilemez ")]
        public string sehiri { get; set; }
        [Display(Name = "Hakkında")]
        [Required(ErrorMessage = "Bu Alan Boş Geçilemez ")]
        public string hakkinda { get; set; }
        public string resim { get; set; }
    }
}
